### PR TITLE
[change] Migrate tslint to eslint

### LINKED ISSUE #168: Migrate TSLint to ESLint
## References
* https://github.com/palantir/tslint/issues/4534

### PR DESCRIPTION
**Pull request by peaceiris**
Close #168

- [lo1tuma/eslint-plugin-mocha: ESLint rules for mocha](https://github.com/lo1tuma/eslint-plugin-mocha)

### CODE REVIEW

**Comment by peaceiris** [comment]
@nwtgck

[The Node CI / build (8.x) failed](https://github.com/nwtgck/piping-server/pull/396/checks?check_run_id=1246305779) due to eslint no longer support Node.js 8. I'm waiting for your opinion. Drop Node.js v8?

cf. [Node.js 8 is no longer supported | Migrating to v7.0.0 - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/user-guide/migrating-to-7.0.0#nodejs-8-is-no-longer-supported)

**Comment by peaceiris** [comment]
@nwtgck

[The Node CI / build (8.x) failed](https://github.com/nwtgck/piping-server/pull/396/checks?check_run_id=1246305779) due to eslint no longer support Node.js 8. I'm waiting for your opinion.

IMO: It is time to drop Node.js v8 and add v14.

cf. [Node.js 8 is no longer supported | Migrating to v7.0.0 - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/user-guide/migrating-to-7.0.0#nodejs-8-is-no-longer-supported)

**Comment by nwtgck** [comment]
@peaceiris 
What kind of tool did you use to write .eslintrc.json? Or you wrote by yourself?

**Comment by peaceiris** [comment]
By myself. I referred to my project setting: [actions-gh-pages/.eslintrc.json at main · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/blob/46b269eb77e5fe6f2fc9c9cc531541227dfeca22/.eslintrc.json)

Since I am using jest as a testing library in the project, I do not know my changes are suitable for mocha.

**Comment by nwtgck** [comment]
Thanks. I'd like to preserve the original tslint.json setting as possible and migrate to eslint.
I'll drop Node.js 8 and add v14.

**Comment by nwtgck** [comment]
Run `npm run lint`in CI for Windows and drop Node.js 8 and add 14.

- #397
- #398

**Comment by nwtgck** [comment]
In my opinion, a favor setting of lint-related technology highly depends on a project author. It might be better to write the author or use auto-migrating from TSLint to ESLint programmatically such as [tslint-to-eslint-config]https://github.com/typescript-eslint/tslint-to-eslint-config). But I'm not sure whether tslint-to-eslint-config became matured or not.

**Comment by peaceiris** [comment]
My changes just followed the recommendation: https://github.com/typescript-eslint/typescript-eslint/blob/c41dbe56e0514846e4d21fc5fcd8847da50e92c6/docs/getting-started/linting/README.md

If you want to use any migration tool, tell me. I will close this.

Also, I tried `tslint-to-eslint-config`.

```console
$ git checkout develop
$ npm ci
$ npx tslint-to-eslint-config --comments
$ cat .eslintrc.js | wc -l
163
```

<details>
<summary>👉 Click to expand .eslintrc.js</summary>

```js
/*
👋 Hi! This file was autogenerated by tslint-to-eslint-config.
https://github.com/typescript-eslint/tslint-to-eslint-config

It represents the closest reasonable ESLint configuration to this
project's original TSLint configuration.

We recommend eventually switching this configuration to extend from
the recommended rulesets in typescript-eslint. 
https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md

Happy linting! 💖
*/
module.exports = {
    "env": {
        "es6": true,
        "node": true
    },
    "extends": [
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": "tsconfig.json",
        "sourceType": "module"
    },
    "plugins": [
        "eslint-plugin-jsdoc",
        "eslint-plugin-prefer-arrow",
        "@typescript-eslint"
    ],
    "rules": {
        "@typescript-eslint/adjacent-overload-signatures": "error",
        "@typescript-eslint/array-type": [
            "error",
            {
                "default": "array"
            }
        ],
        "@typescript-eslint/ban-types": [
            "error",
            {
                "types": {
                    "Object": {
                        "message": "Avoid using the `Object` type. Did you mean `object`?"
                    },
                    "Function": {
                        "message": "Avoid using the `Function` type. Prefer a specific function type, like `() => void`."
                    },
                    "Boolean": {
                        "message": "Avoid using the `Boolean` type. Did you mean `boolean`?"
                    },
                    "Number": {
                        "message": "Avoid using the `Number` type. Did you mean `number`?"
                    },
                    "String": {
                        "message": "Avoid using the `String` type. Did you mean `string`?"
                    },
                    "Symbol": {
                        "message": "Avoid using the `Symbol` type. Did you mean `symbol`?"
                    }
                }
            }
        ],
        "@typescript-eslint/consistent-type-assertions": "error",
        "@typescript-eslint/consistent-type-definitions": "off",
        "@typescript-eslint/dot-notation": "error",
        "@typescript-eslint/naming-convention": "error",
        "@typescript-eslint/no-empty-function": "error",
        "@typescript-eslint/no-empty-interface": "error",
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-namespace": "error",
        "@typescript-eslint/no-parameter-properties": "off",
        "@typescript-eslint/no-unused-expressions": "error",
        "@typescript-eslint/no-use-before-define": "off",
        "@typescript-eslint/no-var-requires": "error",
        "@typescript-eslint/prefer-for-of": "error",
        "@typescript-eslint/prefer-function-type": "error",
        "@typescript-eslint/prefer-namespace-keyword": "error",
        "@typescript-eslint/triple-slash-reference": [
            "error",
            {
                "path": "always",
                "types": "prefer-import",
                "lib": "always"
            }
        ],
        "@typescript-eslint/unified-signatures": "error",
        "comma-dangle": "error",
        "complexity": "off",
        "constructor-super": "error",
        "eqeqeq": [
            "error",
            "always"
        ],
        "guard-for-in": "error",
        "id-blacklist": [
            "error",
            "any",
            "Number",
            "number",
            "String",
            "string",
            "Boolean",
            "boolean",
            "Undefined",
            "undefined"
        ],
        "id-match": "error",
        "jsdoc/check-alignment": "error",
        "jsdoc/check-indentation": "error",
        "jsdoc/newline-after-description": "error",
        "max-classes-per-file": [
            "error",
            1
        ],
        "new-parens": "error",
        "no-bitwise": "error",
        "no-caller": "error",
        "no-cond-assign": "error",
        "no-console": "error",
        "no-debugger": "error",
        "no-empty": "error",
        "no-eval": "error",
        "no-fallthrough": "off",
        "no-invalid-this": "off",
        "no-new-wrappers": "error",
        "no-shadow": [
            "error",
            {
                "hoist": "all"
            }
        ],
        "no-throw-literal": "error",
        "no-trailing-spaces": "error",
        "no-undef-init": "error",
        "no-underscore-dangle": "error",
        "no-unsafe-finally": "error",
        "no-unused-labels": "error",
        "no-var": "error",
        "object-shorthand": "off",
        "one-var": [
            "error",
            "never"
        ],
        "prefer-arrow/prefer-arrow-functions": "error",
        "prefer-const": "error",
        "radix": "error",
        "spaced-comment": [
            "error",
            "always",
            {
                "markers": [
                    "/"
                ]
            }
        ],
        "use-isnan": "error",
        "valid-typeof": "off"
    }
};
```

</details>

**Comment by peaceiris** [comment]
> edit: I'm not sure that Windows recognize `./{src,test}/**/*.ts`, so I added npm run lint in CI for Windows.

It works well.
https://github.com/peaceiris/actions-gh-pages/runs/1251360281#step:11:15

**Comment by nwtgck** [comment]
Thanks. Auto-generated config file should be long, but I can adjust it. I'll try to generate automatically by tslint-to-eslint-config and consider.

**Pull request closed without merging**
