### PR TITLE
Simplify generate-version

### PR DESCRIPTION
**Pull request by jsarenik**
Get rid of `cross-var` and all its dependencies. Breathe.

@nwtgck By the way, thank you Rio for a wonderful piece of software!

### CODE REVIEW

**Comment by nwtgck** [comment]
Thank you so much, @jsarenik !

I am not sure why `cross-var` should be removed. It is `devDependencies `, so removing it doesn't contribute to reducing the size. Generally, dependent can be a vulnerability, I know `cross-var`'s last publish is 2 years ago, but it's used well.

I'd like to write "generate-version" inline because it is not so a big task and it clarifies what kind of thing is conducted in this case generating version. Of course, one day when it has more logic, the generation of version should be separated into a single script or something. Maybe it's a little hard to read.

Here is my alternative to get rid of `cross-var`. I tested it works.

```json
"generate-version": "node -pe '`export const VERSION = \"${process.env.npm_package_version}\";`' > src/version.ts",
```

But the way, thank you so much for your contribution.

**Comment by jsarenik** [comment]
As far as I understand, the only place where it was used was generating the version file.

**Comment by jsarenik** [comment]
> Here is my alternative to get rid of `cross-var`. I tested it works.
> 
> ```json
> "generate-version": "node -pe '`export const VERSION = \"${process.env.npm_package_version}\";`' > src/version.ts",
> ```

Sure! This is great. I just twisted my shell way of thinking into that `gen-version.js`.
Thank you for this simpler approach.

**Comment by jsarenik** [comment]
@nwtgck see af1da05

**Comment by jsarenik** [comment]
@nwtgck See the latest, 5c1e55a

**Comment by nwtgck** [comment]
@jsarenik Thanks! I'll merge this.

**Pull request merged**
